# Generated by Django 4.2.16 on 2026-07-23 13:53

from django.db import migrations, models


def drop_codigo_unique_index(apps, schema_editor):
    schema_editor.execute("ALTER TABLE personas DROP CONSTRAINT IF EXISTS personas_codigo_key")


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_make_unidad_required'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='persona',
                    name='codigo',
                    field=models.CharField(max_length=20, verbose_name='Código'),
                ),
            ],
            database_operations=[
                migrations.RunPython(drop_codigo_unique_index, migrations.RunPython.noop),
            ],
        ),
    ]
