# Generated by Django 4.2.16 on 2026-10-01 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0002_migrar_datos_iniciales'),
        ('documentos', '0006_alter_tipodocumento_options_documento_subido_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrigenArchivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('google_drive', 'Google Drive'), ('s3', 'Almacenamiento S3 compatible'), ('onedrive', 'OneDrive / SharePoint'), ('carpeta', 'Carpeta local o de red')], default='google_drive', max_length=20)),
                ('identificador', models.CharField(blank=True, default='', help_text='Carpeta de Drive, o bucket/prefijo S3, o ruta local', max_length=500)),
                ('drive_compartido', models.BooleanField(default=False, help_text='Marcar si el identificador es un Drive compartido y no una Drive personal')),
                ('credencial_ref', models.CharField(blank=True, default='', help_text='Alias del secreto (ruta del JSON o variable de entorno). Nunca la clave en sí', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('marca_tiempo', models.DateTimeField(blank=True, help_text='Última modificación importada. Solo se usa como pre-filtro', null=True)),
                ('ultima_sincronizacion', models.DateTimeField(blank=True, null=True)),
                ('ultimo_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='origen_archivos', to='unidades.unidad')),
            ],
            options={
                'verbose_name': 'origen de archivos',
                'verbose_name_plural': 'origenes de archivos',
                'db_table': 'origen_archivos',
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='origen_id',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador del archivo en el proveedor de origen (evita reimportar)', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Sincronizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('exitosa', 'Exitosa'), ('con_errores', 'Con errores'), ('fallida', 'Fallida')], default='exitosa', max_length=20)),
                ('iniciada_en', models.DateTimeField(auto_now_add=True)),
                ('encontrada', models.IntegerField(default=0)),
                ('procesados', models.IntegerField(default=0)),
                ('omitidos_ya_importados', models.IntegerField(default=0)),
                ('omitidos_sin_codigo', models.IntegerField(default=0)),
                ('omitidos_sin_persona', models.IntegerField(default=0)),
                ('omitidos_tamano', models.IntegerField(default=0)),
                ('omitidos_no_pdf', models.IntegerField(default=0)),
                ('paginas', models.IntegerField(default=0)),
                ('errores', models.IntegerField(default=0)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('detalle', models.JSONField(blank=True, default=list)),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sincronizaciones', to='documentos.origenarchivos')),
            ],
            options={
                'verbose_name': 'sincronización',
                'verbose_name_plural': 'sincronizaciones',
                'db_table': 'sincronizaciones',
                'ordering': ['-iniciada_en'],
            },
        ),
    ]
