# Generated by Django 4.2.16 on 2026-07-28 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentos', '0005_remove_campos_avanzados'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'ordering': ['nombre'], 'verbose_name': 'tipo de documento', 'verbose_name_plural': 'tipos de documento'},
        ),
        migrations.AddField(
            model_name='documento',
            name='subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
    ]
